project:
  type: website
  output-dir: docs

website:
  title: "David Schweizer"
  search: false
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, David Schweizer"
  navbar:
    right:
      # - href: index.qmd
      #   text: "home"
      - href: index_research.qmd
        text: "research"
      - href: teaching.qmd
        text: "teaching"
        
format:
  html:
    theme: 
      light: journal
      #dark: darkly
    css: [styles.css, icons.css]

editor: visual