---
title: ""
---

## Working Papers

::: {.callout-note icon="false" appearance="simple"}
**No Planet B? Climate Change and Party Competition**
:::

**Abstract:** Climate change, one of the biggest challenges of our time, increasingly shapes party competition in Western Europe. Particularly tangible phenomena of climate change are natural disasters. Parties' responses to these climate change-related events have the potential to shape public opinion and individual attitudes on this critical matter. While scholars have examined the effect of natural disasters on the latter, the effect on political parties themselves remains understudied. I argue that such drastic events have a differentiated impact. Following these events, the salience of climate change issues should increase among all political parties. In contrast, I expect that party competition on these issues becomes more polarized, i.e., that parties take more extreme positions. I test these expectations by examining the effect of natural disasters such as severe floods or draughts in six Western European countries between 2012 and 2022. The analysis is based on press releases by the main political parties regularly represented in the respective national parliaments, which allows me to study both short- and long-term effects. Specifically, I construct a time-series cross-sectional party-month data set. Using matching methods, I then exploit the occurrence of natural disasters as quasi-natural experiments for causal effect estimation. The results contribute to our understanding of the new divide between green and populist radical right parties and the polarization of party systems.

::: {.callout-note icon="false" appearance="simple"}
**Worried About Climate Change and Unsatisfied With Democracy?** with [Jan Menzner](https://janmenzner.org/home/)
:::

**Abstract:**\
Climate change is widely perceived as the most significant challenge of this century. We argue the more citizens are concerned about the effects of climate change and unsatisfied with their government's climate politics, the greater their dissatisfaction with democracy and propensity to hold anti-elitist views. We draw on two German panel data sets to address these understudied relationships. First, we examine the main relationship between being worried about climate change and satisfaction with democracy as it exists in Germany using data from three waves (2010, 2016, 2020) of the Socio-Economic Panel. We reproduce this analysis with data from the German Longitudinal Election Study (GLES) Panel, ranging from 2017 to 2022. Further, using three GLES waves, we study how satisfaction with the government's climate action affects general satisfaction with democracy. Finally, we investigate the association between prioritizing climate action and multiple dimensions of populism, focusing on anti-elitism. Against the backdrop of exacerbating climate change, our research contributes to understanding how worries about climate change and dissatisfaction with political action might translate into disenchantment with the democratic system itself.

### Selected Work in Progress

::: {.callout-note icon="false" appearance="simple"}
**A Natural Divide? Climate Change and Party Unity**
:::

::: {.callout-note icon="false" appearance="simple"}
**Forest Loss and Party Competition: Examining the Local Politics of Climate Change**
:::

::: {.callout-note icon="false" appearance="simple"}
**The Differentiated Impact of Perceived EU Regional Policy on Citizen's Position on European Integration** with [Marc Debus](https://www.sowi.uni-mannheim.de/debus/team/lehrstuhlinhaber/)
:::
