---
title: "No Planet B? Climate Change and Party Competition"
author: 
  - David Schweizer
  - affiliation: University of Mannheim
---

## Abstract

Climate change, one of the biggest challenges of our time, increasingly shapes party competition in Western Europe. Particularly tangible phenomena of climate change are natural disasters. Parties' responses to these climate change-related events have the potential to shape public opinion and individual attitudes on this critical matter. While scholars have examined the effect of natural disasters on the latter, the effect on political parties themselves remains understudied. I argue that such drastic events have a differentiated impact. Following these events, the salience of climate change issues should increase among all political parties. In contrast, I expect that party competition on these issues becomes more polarized, i.e., that parties take more extreme positions. I test these expectations by examining the effect of natural disasters such as severe floods or draughts in six Western European countries between 2012 and 2022. The analysis is based on press releases by the main political parties regularly represented in the respective national parliaments, which allows me to study both short- and long-term effects. Specifically, I construct a time-series cross-sectional party-month data set. Using matching methods, I then exploit the occurrence of natural disasters as quasi-natural experiments for causal effect estimation. The results contribute to our understanding of the new divide between green and populist radical right parties and the polarization of party systems.